version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: iot-dashboard-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  
  mongo-express:
    image: mongo-express:latest
    container_name: iot-dashboard-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  mongo-data: